#
# Copyright 2017-2018 the original author or authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  port: 7777

spring:
  reactor:
    stacktrace-mode:
      enabled: true
  jackson:
    default-property-inclusion: non_default
    date-format: yyyy-MM-dd'T'HH:mm:ss
    joda-date-time-format: yyyy-MM-dd'T'HH:mm:ss
    property-naming-strategy: SNAKE_CASE

duic:
  dbms: MongoDB
  root-email: kevinz@weghst.com
  root-password: 123456
  jwt:
    secret: U2FsdGVkX1/jO0KlWumac4yDM8rOgWPkaV0KrSHDynWOP6n8FMJB9uSc8EW/qM+VagrMBAXGpyw=
    expires-in: 7200
  app:
    watch:
      updated:
        fixed-delay: 5000
      deleted:
        fixed-delay: 600000
